// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.15.8
// source: mypb.proto

package mypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jobid        int32  `protobuf:"varint,1,opt,name=jobid,proto3" json:"jobid,omitempty"`
	Jobname      string `protobuf:"bytes,2,opt,name=jobname,proto3" json:"jobname,omitempty"`
	NextExecTime string `protobuf:"bytes,3,opt,name=next_exec_time,json=nextExecTime,proto3" json:"next_exec_time,omitempty"`
	Interval     string `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mypb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mypb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_mypb_proto_rawDescGZIP(), []int{0}
}

func (x *JobInfo) GetJobid() int32 {
	if x != nil {
		return x.Jobid
	}
	return 0
}

func (x *JobInfo) GetJobname() string {
	if x != nil {
		return x.Jobname
	}
	return ""
}

func (x *JobInfo) GetNextExecTime() string {
	if x != nil {
		return x.NextExecTime
	}
	return ""
}

func (x *JobInfo) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

type DispatchJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobInfo *JobInfo `protobuf:"bytes,1,opt,name=job_info,json=jobInfo,proto3" json:"job_info,omitempty"`
}

func (x *DispatchJobRequest) Reset() {
	*x = DispatchJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mypb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DispatchJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchJobRequest) ProtoMessage() {}

func (x *DispatchJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mypb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchJobRequest.ProtoReflect.Descriptor instead.
func (*DispatchJobRequest) Descriptor() ([]byte, []int) {
	return file_mypb_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchJobRequest) GetJobInfo() *JobInfo {
	if x != nil {
		return x.JobInfo
	}
	return nil
}

type DispatchJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DispatchJobResponse) Reset() {
	*x = DispatchJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mypb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DispatchJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchJobResponse) ProtoMessage() {}

func (x *DispatchJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mypb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchJobResponse.ProtoReflect.Descriptor instead.
func (*DispatchJobResponse) Descriptor() ([]byte, []int) {
	return file_mypb_proto_rawDescGZIP(), []int{2}
}

func (x *DispatchJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JobStartedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jobid int32 `protobuf:"varint,1,opt,name=jobid,proto3" json:"jobid,omitempty"`
}

func (x *JobStartedRequest) Reset() {
	*x = JobStartedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mypb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobStartedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStartedRequest) ProtoMessage() {}

func (x *JobStartedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mypb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStartedRequest.ProtoReflect.Descriptor instead.
func (*JobStartedRequest) Descriptor() ([]byte, []int) {
	return file_mypb_proto_rawDescGZIP(), []int{3}
}

func (x *JobStartedRequest) GetJobid() int32 {
	if x != nil {
		return x.Jobid
	}
	return 0
}

type JobStartedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *JobStartedResponse) Reset() {
	*x = JobStartedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mypb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobStartedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStartedResponse) ProtoMessage() {}

func (x *JobStartedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mypb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStartedResponse.ProtoReflect.Descriptor instead.
func (*JobStartedResponse) Descriptor() ([]byte, []int) {
	return file_mypb_proto_rawDescGZIP(), []int{4}
}

func (x *JobStartedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JobCompletedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jobid     int32  `protobuf:"varint,1,opt,name=jobid,proto3" json:"jobid,omitempty"`
	Jobresult string `protobuf:"bytes,2,opt,name=jobresult,proto3" json:"jobresult,omitempty"`
}

func (x *JobCompletedRequest) Reset() {
	*x = JobCompletedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mypb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCompletedRequest) ProtoMessage() {}

func (x *JobCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mypb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCompletedRequest.ProtoReflect.Descriptor instead.
func (*JobCompletedRequest) Descriptor() ([]byte, []int) {
	return file_mypb_proto_rawDescGZIP(), []int{5}
}

func (x *JobCompletedRequest) GetJobid() int32 {
	if x != nil {
		return x.Jobid
	}
	return 0
}

func (x *JobCompletedRequest) GetJobresult() string {
	if x != nil {
		return x.Jobresult
	}
	return ""
}

type JobCompletedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *JobCompletedResponse) Reset() {
	*x = JobCompletedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mypb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCompletedResponse) ProtoMessage() {}

func (x *JobCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mypb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCompletedResponse.ProtoReflect.Descriptor instead.
func (*JobCompletedResponse) Descriptor() ([]byte, []int) {
	return file_mypb_proto_rawDescGZIP(), []int{6}
}

func (x *JobCompletedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WorkerHelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerURI string `protobuf:"bytes,1,opt,name=workerURI,proto3" json:"workerURI,omitempty"`
}

func (x *WorkerHelloRequest) Reset() {
	*x = WorkerHelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mypb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHelloRequest) ProtoMessage() {}

func (x *WorkerHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mypb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHelloRequest.ProtoReflect.Descriptor instead.
func (*WorkerHelloRequest) Descriptor() ([]byte, []int) {
	return file_mypb_proto_rawDescGZIP(), []int{7}
}

func (x *WorkerHelloRequest) GetWorkerURI() string {
	if x != nil {
		return x.WorkerURI
	}
	return ""
}

type WorkerHelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *WorkerHelloResponse) Reset() {
	*x = WorkerHelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mypb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHelloResponse) ProtoMessage() {}

func (x *WorkerHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mypb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHelloResponse.ProtoReflect.Descriptor instead.
func (*WorkerHelloResponse) Descriptor() ([]byte, []int) {
	return file_mypb_proto_rawDescGZIP(), []int{8}
}

func (x *WorkerHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mypb_proto protoreflect.FileDescriptor

var file_mypb_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x79, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x79,
	0x70, 0x62, 0x22, 0x7b, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x6a, 0x6f, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6a, 0x6f,
	0x62, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x6f, 0x62, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a,
	0x0e, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x65, 0x78, 0x74, 0x45, 0x78, 0x65, 0x63, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22,
	0x3e, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x79, 0x70, 0x62, 0x2e, 0x4a,
	0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x2f, 0x0a, 0x13, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x29, 0x0a, 0x11, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x4a,
	0x6f, 0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x49, 0x0a, 0x13, 0x4a,
	0x6f, 0x62, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6a, 0x6f, 0x62, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6a, 0x6f, 0x62,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x30, 0x0a, 0x14, 0x4a, 0x6f, 0x62, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x12, 0x57, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x55, 0x52, 0x49, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x55, 0x52, 0x49, 0x22, 0x2f, 0x0a, 0x13,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x52, 0x0a,
	0x0c, 0x4a, 0x6f, 0x62, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x12, 0x42, 0x0a,
	0x0b, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x4a, 0x6f, 0x62, 0x12, 0x18, 0x2e, 0x6d,
	0x79, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x79, 0x70, 0x62, 0x2e, 0x44, 0x69,
	0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x93, 0x01, 0x0a, 0x09, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x3f, 0x0a, 0x0a, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x17, 0x2e,
	0x6d, 0x79, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x79, 0x70, 0x62, 0x2e, 0x4a, 0x6f,
	0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x45, 0x0a, 0x0c, 0x4a, 0x6f, 0x62, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x12, 0x19, 0x2e, 0x6d, 0x79, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x62, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x79,
	0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x62, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x4f, 0x0a, 0x09, 0x45, 0x74, 0x63, 0x64, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x42, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x18, 0x2e, 0x6d, 0x79, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x6d, 0x79, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x62, 0x6c, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f,
	0x73, 0x2f, 0x6d, 0x79, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x6d, 0x79, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mypb_proto_rawDescOnce sync.Once
	file_mypb_proto_rawDescData = file_mypb_proto_rawDesc
)

func file_mypb_proto_rawDescGZIP() []byte {
	file_mypb_proto_rawDescOnce.Do(func() {
		file_mypb_proto_rawDescData = protoimpl.X.CompressGZIP(file_mypb_proto_rawDescData)
	})
	return file_mypb_proto_rawDescData
}

var file_mypb_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mypb_proto_goTypes = []interface{}{
	(*JobInfo)(nil),              // 0: mypb.JobInfo
	(*DispatchJobRequest)(nil),   // 1: mypb.DispatchJobRequest
	(*DispatchJobResponse)(nil),  // 2: mypb.DispatchJobResponse
	(*JobStartedRequest)(nil),    // 3: mypb.JobStartedRequest
	(*JobStartedResponse)(nil),   // 4: mypb.JobStartedResponse
	(*JobCompletedRequest)(nil),  // 5: mypb.JobCompletedRequest
	(*JobCompletedResponse)(nil), // 6: mypb.JobCompletedResponse
	(*WorkerHelloRequest)(nil),   // 7: mypb.WorkerHelloRequest
	(*WorkerHelloResponse)(nil),  // 8: mypb.WorkerHelloResponse
}
var file_mypb_proto_depIdxs = []int32{
	0, // 0: mypb.DispatchJobRequest.job_info:type_name -> mypb.JobInfo
	1, // 1: mypb.JobScheduler.DispatchJob:input_type -> mypb.DispatchJobRequest
	3, // 2: mypb.JobStatus.JobStarted:input_type -> mypb.JobStartedRequest
	5, // 3: mypb.JobStatus.JobCompleted:input_type -> mypb.JobCompletedRequest
	7, // 4: mypb.EtcdHello.WorkerHello:input_type -> mypb.WorkerHelloRequest
	2, // 5: mypb.JobScheduler.DispatchJob:output_type -> mypb.DispatchJobResponse
	4, // 6: mypb.JobStatus.JobStarted:output_type -> mypb.JobStartedResponse
	6, // 7: mypb.JobStatus.JobCompleted:output_type -> mypb.JobCompletedResponse
	8, // 8: mypb.EtcdHello.WorkerHello:output_type -> mypb.WorkerHelloResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mypb_proto_init() }
func file_mypb_proto_init() {
	if File_mypb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mypb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mypb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DispatchJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mypb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DispatchJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mypb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobStartedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mypb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobStartedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mypb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobCompletedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mypb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobCompletedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mypb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerHelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mypb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerHelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mypb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_mypb_proto_goTypes,
		DependencyIndexes: file_mypb_proto_depIdxs,
		MessageInfos:      file_mypb_proto_msgTypes,
	}.Build()
	File_mypb_proto = out.File
	file_mypb_proto_rawDesc = nil
	file_mypb_proto_goTypes = nil
	file_mypb_proto_depIdxs = nil
}
